export const BRAND = {
  wordmark: "MARELI",
  logo: "/brand/logo-mareli.jpg",
  footerBrand: "MARELI ARTE",
  phrase: "Trazendo arte e beleza para o seu lar!",
  instagramLabel: "Instagram",
  whatsappLabel: "WhatsApp",
  backTop: "Voltar ao topo ↑",
  location: "Curitiba e Região Metropolitana",
  hero: {
    kicker: "Novos · usados · restaurados",
    titleLine: "ARTE E BELEZA",
    titleAccent: "para o seu lar",
    description:
      "Móveis com história, projetos planejados e peças restauradas com carinho — para quem quer um lar com presença.",
    primaryCta: "Ver móveis",
    secondaryCta: "Conhecer a Mareli",
    image:
      "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1600",
    imageAlt: "Ambiente aconchegante com móveis de madeira e luz quente.",
  },
  trust: [
    { label: "Escolha sob medida", detail: "filtre pelo seu vão" },
    { label: "Novos e restaurados", detail: "peças com história" },
    { label: "Projetos planejados", detail: "sob encomenda" },
    { label: "Curitiba e região", detail: "entrega cuidadosa" },
  ],
  manifesto: {
    kicker: "Manifesto",
    title: "A Mareli traz arte para dentro de casa",
    description:
      "Cada móvel carrega ofício, madeira e intenção. Seja novo, usado ou restaurado, escolhemos peças que deixam o lar mais belo e acolhedor.",
    pillars: [
      {
        n: "01",
        title: "Ofício",
        text: "Restauração atenta, acabamento honesto e respeito à história de cada peça.",
        tone: "ivory" as const,
      },
      {
        n: "02",
        title: "Beleza",
        text: "Curadoria que equilibra presença visual, proporção e aconchego no ambiente.",
        tone: "burgundy" as const,
      },
      {
        n: "03",
        title: "Lar",
        text: "Móveis pensados para o dia a dia — morar bem também é se reconhecer em casa.",
        tone: "ivory" as const,
      },
    ],
  },
  catalog: {
    kicker: "Seleção Mareli",
    title: "Móveis em destaque",
    note: "Peças inspiradas no acervo Mareli Arte — novos, usados e restaurados.",
    searchLabel: "Buscar nos móveis",
    searchPlaceholder: "Buscar móvel ou ambiente",
    categoryLabel: "Filtrar por categoria",
    styleLabel: "Filtrar por estilo",
    sortLabel: "Ordenar móveis",
    priceLabel: "Faixa de preço:",
    emptyTitle: "Ainda não encontramos esse móvel",
    emptyText: "Tente outro termo ou remova alguns filtros para reencontrar a peça certa.",
    clearFilters: "Limpar filtros",
  },
  categories: {
    kicker: "Para explorar",
    title: "CATEGORIAS",
    text: "Do living ao quarto — clique e veja o que cabe no seu espaço.",
    chips: [
      {
        label: "Mesas",
        href: "/categoria/mesas",
        image: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
      {
        label: "Roupeiros",
        href: "/categoria/estantes-e-racks",
        image: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
      {
        label: "Poltronas",
        href: "/categoria/cadeiras-e-poltronas",
        image: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
      {
        label: "Sofás",
        href: "/categoria/sofas",
        image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
    ],
    soon: "Novas peças em breve",
  },
  editorial: {
    kicker: "Arte para morar",
    title: "Escolha sentir em casa.",
    text: "Móveis que unem madeira, memória e beleza — do vintage restaurado ao planejado sob medida.",
  },
  testimonials: {
    kicker: "Impressões",
    title: "Lares com a Mareli",
    items: [
      {
        quote:
          "A peça restaurada chegou impecável e parece ter nascido na sala. Texto ilustrativo da experiência Mareli.",
        author: "Cliente Mareli",
      },
      {
        quote:
          "Atendimento atento e móveis com alma. Exemplo demonstrativo, não uma avaliação verificada.",
        author: "Comunidade Mareli",
      },
      {
        quote:
          "Encontrei o equilíbrio entre beleza e função. Texto de exemplo para esta demonstração.",
        author: "Curitiba",
      },
    ],
  },
  journal: {
    kicker: "Inspiração",
    title: "Ambientes Mareli",
    articles: [
      {
        category: "Vintage",
        title: "Peças que envelhecem bem",
        text: "Restauração cuidadosa para móveis que ganham nova vida no lar.",
        image:
          "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Móvel de madeira vintage em ambiente iluminado.",
      },
      {
        category: "Madeira",
        title: "O tempo das fibras visíveis",
        text: "Veios, nós e tom natural — quando o material honesto vira decoração.",
        image:
          "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Detalhe de madeira e móvel clássico.",
      },
      {
        category: "Lar",
        title: "Beleza no cotidiano",
        text: "Escolher móveis também é cuidar de como a casa acolhe o dia a dia.",
        image:
          "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Sala aconchegante com móveis de madeira.",
      },
    ],
  },
  contact: {
    kicker: "Vamos conversar",
    title: "Chame a Mareli e conte o que o seu lar precisa.",
    text: "Novos, usados, restaurados ou planejados — compartilhe medidas, ideias ou tire dúvidas.",
    name: "Nome",
    email: "E-mail",
    whatsapp: "WhatsApp",
    whatsappOptional: "(opcional)",
    message: "Mensagem",
    submit: "Enviar mensagem",
    disclaimer: "Ao enviar, sua mensagem é salva de forma privada para retorno da Mareli Arte.",
  },
  bag: {
    kicker: "Sua seleção",
    title: "Sacola Mareli",
    empty: "Sua sacola está esperando um móvel especial.",
    subtotal: "Subtotal",
    checkout: "Finalizar compra",
  },
  footer: {
    navTitle: "Navegue",
    serviceTitle: "Atendimento",
    serviceText: "Curitiba e Região Metropolitana. A Mareli Arte recebe cada mensagem com atenção.",
    copy: "© 2026 MARELI ARTE",
  },
} as const;

export const FEATURED_PIECES = [
  {
    slug: "par-mesas-auxiliares",
    name: "Par de Mesas Auxiliares",
    meta: "Mesas · Sala · Madeira",
    category: "Mesas",
    style: "Clássico",
    priceCents: 89000,
    brand: "Mareli Arte",
    size: "Compacto",
    color: "Imbuia",
    condition: "VERY_GOOD" as const,
    categorySlug: "mesas",
    description: "Par de mesas auxiliares em madeira, ideais para sala — acabamento quente e proporção delicada.",
    image:
      "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Par de mesas auxiliares em madeira escura.",
    widthCm: 45,
    heightCm: 55,
    depthCm: 45,
  },
  {
    slug: "roupeiro-vintage",
    name: "Roupeiro Vintage",
    meta: "Roupeiro · Quarto · Retrô",
    category: "Estantes e racks",
    style: "Vintage",
    priceCents: 249000,
    brand: "Mareli Arte",
    size: "Grande",
    color: "Imbuia",
    condition: "VINTAGE" as const,
    categorySlug: "estantes-e-racks",
    description: "Roupeiro vintage restaurado, portas sólidas e presença clássica para o quarto.",
    image:
      "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Roupeiro de madeira vintage.",
    widthCm: 120,
    heightCm: 200,
    depthCm: 55,
  },
  {
    slug: "penteadeira-vintage",
    name: "Penteadeira Vintage",
    meta: "Penteadeira · Quarto · Especial",
    category: "Mesas",
    style: "Vintage",
    priceCents: 179000,
    brand: "Mareli Arte",
    size: "Médio",
    color: "Natural",
    condition: "EXCELLENT" as const,
    categorySlug: "mesas",
    description: "Penteadeira com espelho e gavetas — peça única com charme de época.",
    image:
      "https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Penteadeira vintage com espelho.",
    widthCm: 100,
    heightCm: 150,
    depthCm: 45,
  },
  {
    slug: "guarda-roupa-modulado",
    name: "Guarda-roupa Modulado",
    meta: "Planejado · Quarto · Sob medida",
    category: "Estantes e racks",
    style: "Contemporâneo",
    priceCents: 389000,
    brand: "Mareli Arte",
    size: "Grande",
    color: "Nogueira",
    condition: "NEW_WITH_TAG" as const,
    categorySlug: "estantes-e-racks",
    description: "Guarda-roupa modulado sob projeto — organização e acabamento sob medida.",
    image:
      "https://images.pexels.com/photos/6585764/pexels-photo-6585764.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Guarda-roupa modulado em madeira.",
    widthCm: 240,
    heightCm: 220,
    depthCm: 60,
  },
  {
    slug: "sofa-linho-areia",
    name: "Sofá Linho Areia",
    meta: "Sofá · Sala · Linho",
    category: "Sofás",
    style: "Contemporâneo",
    priceCents: 489000,
    brand: "Mareli Arte",
    size: "Grande",
    color: "Areia",
    condition: "EXCELLENT" as const,
    categorySlug: "sofas",
    description: "Sofá de três lugares em linho, assento profundo e estrutura em madeira.",
    image:
      "https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Sofá claro de linho em sala iluminada.",
    widthCm: 220,
    heightCm: 85,
    depthCm: 95,
  },
  {
    slug: "mesa-jantar-carvalho",
    name: "Mesa de Jantar Carvalho",
    meta: "Mesa · Jantar · Carvalho",
    category: "Mesas",
    style: "Clássico",
    priceCents: 329000,
    brand: "Mareli Arte",
    size: "Grande",
    color: "Natural",
    condition: "NEW_WITH_TAG" as const,
    categorySlug: "mesas",
    description: "Mesa de jantar em madeira com veio aparente e presença acolhedora.",
    image:
      "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Mesa de jantar em madeira.",
    widthCm: 180,
    heightCm: 76,
    depthCm: 90,
  },
] as const;
