export const BRAND = {
  wordmark: "MARELI",
  logo: "/brand/logo-mareli.jpg",
  footerBrand: "MARELI ARTE",
  phrase: "O espaço que você habita, com intenção.",
  instagramLabel: "Instagram",
  whatsappLabel: "WhatsApp",
  backTop: "Voltar ao topo ↑",
  hero: {
    kicker: "Design para morar",
    titleLine: "MÓVEIS COM",
    titleAccent: "presença",
    description:
      "Seleção de sofás, mesas, camas e peças de madeira com acabamento honesto — para ambientes que respiram calma e personalidade.",
    primaryCta: "Explorar móveis",
    secondaryCta: "Conhecer a Mareli",
    image:
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1600",
    imageAlt:
      "Sala de estar acolhedora com sofá de linho, mesa de centro em madeira e luz natural.",
  },
  trust: [
    { label: "Escolha sob medida", detail: "filtre pelo seu vão" },
    { label: "Móveis com curadoria", detail: "selecionados à mão" },
    { label: "Pagamento seguro", detail: "Pix e cartão" },
    { label: "Entrega cuidadosa", detail: "para todo o Brasil" },
  ],
  manifesto: {
    kicker: "Manifesto",
    title: "A Mareli é o lugar que você escolhe",
    description:
      "Não existe um único estilo de casa certo. Existe o desejo de viver em um ambiente que acolhe quem você é — com madeira, textura, proporção e luz.",
    pillars: [
      {
        n: "01",
        title: "Espaço",
        text: "Móveis pensados para circular, conviver e descansar — sem ocupar o ambiente de forma gratuita.",
        tone: "ivory" as const,
      },
      {
        n: "02",
        title: "Ofício",
        text: "Curadoria atenta a estrutura, acabamento, madeira e tudo o que faz uma peça durar além da tendência.",
        tone: "burgundy" as const,
      },
      {
        n: "03",
        title: "Moradia",
        text: "Mobiliar também é cuidar do bem-estar diário — conforto, silêncio visual e sensação de chegar em casa.",
        tone: "ivory" as const,
      },
    ],
  },
  catalog: {
    kicker: "Seleção da semana",
    title: "Móveis em destaque",
    note: "Peças e valores apresentados apenas para demonstração.",
    searchLabel: "Buscar nos móveis",
    searchPlaceholder: "Buscar móvel ou ambiente",
    categoryLabel: "Filtrar por categoria",
    styleLabel: "Filtrar por estilo",
    sortLabel: "Ordenar móveis",
    priceLabel: "Faixa de preço:",
    emptyTitle: "Ainda não encontramos esse móvel",
    emptyText: "Tente outro termo ou remova alguns filtros para reencontrar a peça certa para o seu espaço.",
    clearFilters: "Limpar filtros",
  },
  categories: {
    kicker: "Para explorar",
    title: "CATEGORIAS",
    text: "Clique em uma categoria e veja os móveis correspondentes no catálogo.",
    chips: [
      {
        label: "Sofás",
        href: "/categoria/sofas",
        image: "https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
      {
        label: "Mesas",
        href: "/categoria/mesas",
        image: "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
      {
        label: "Poltronas",
        href: "/categoria/cadeiras-e-poltronas",
        image: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
      {
        label: "Camas",
        href: "/categoria/camas",
        image: "https://images.pexels.com/photos/813691/pexels-photo-813691.jpeg?auto=compress&cs=tinysrgb&w=800",
      },
    ],
    soon: "Novas categorias em breve",
  },
  editorial: {
    kicker: "Viver como gesto",
    title: "Escolha habitar.",
    text: "O móvel pode ser abrigo, memória, encontro e pausa. Escolha aquilo que faz sua casa parecer sua — sem catálogo genérico, com espaço para a sua própria narrativa.",
  },
  testimonials: {
    kicker: "Impressões",
    title: "Lares em transformação",
    items: [
      {
        quote:
          "O sofá chegou com a proporção que a sala precisava. Parecia que já morava aqui há anos — texto ilustrativo da experiência Mareli.",
        author: "Cliente Mareli",
      },
      {
        quote:
          "A mesa de jantar trouxe calma para o refeitório. Exemplo demonstrativo, não uma avaliação verificada.",
        author: "Comunidade Mareli",
      },
      {
        quote:
          "Gostei de sentir que os móveis conversam com a casa, não com um showroom frio. Texto de exemplo para esta demonstração.",
        author: "Morador Mareli",
      },
    ],
  },
  journal: {
    kicker: "Inspiração",
    title: "Diário Mareli",
    articles: [
      {
        category: "Ambientes",
        title: "Menos volume, mais permanência",
        text: "Um olhar sobre móveis que envelhecem bem e deixam a sala respirar.",
        image:
          "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Sala de estar minimalista com poltrona e luminária de chão.",
      },
      {
        category: "Madeira",
        title: "O tempo das fibras visíveis",
        text: "Veios, nós e tom natural — quando o material honesto vira decoração.",
        image:
          "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Mesa de jantar em madeira maciça com cadeiras escandinavas.",
      },
      {
        category: "Comportamento",
        title: "Mobiliar a própria rotina",
        text: "Uma reflexão sobre casa como extensão do dia a dia, com liberdade para mudar de ideia e de layout.",
        image:
          "https://images.pexels.com/photos/813691/pexels-photo-813691.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Quarto aconchegante com cama de madeira e iluminação suave.",
      },
    ],
  },
  contact: {
    kicker: "Vamos conversar",
    title: "O seu ambiente também inspira a Mareli.",
    text: "Conte o que você procura, compartilhe medidas ou deixe seu recado. Vamos receber sua mensagem com atenção.",
    name: "Nome",
    email: "E-mail",
    whatsapp: "WhatsApp",
    whatsappOptional: "(opcional)",
    message: "Mensagem",
    submit: "Enviar mensagem",
    disclaimer: "Ao enviar, sua mensagem é salva de forma privada para retorno da Mareli Arte.",
  },
  bag: {
    kicker: "Sua seleção",
    title: "Sacola Mareli",
    empty: "Sua sacola está esperando um móvel especial.",
    subtotal: "Subtotal",
    checkout: "Finalizar compra",
  },
  footer: {
    navTitle: "Navegue",
    serviceTitle: "Atendimento",
    serviceText: "A Mareli Arte recebe cada mensagem com atenção e cuidado.",
    copy: "© 2026 MARELI ARTE",
  },
} as const;

export const FEATURED_PIECES = [
  {
    slug: "sofa-linho-areia",
    name: "Sofá Linho Areia",
    meta: "Sofá · Sala · Linho",
    category: "Sofás",
    style: "Contemporâneo",
    priceCents: 489000,
    brand: "Mareli Arte",
    size: "Grande",
    color: "Areia",
    condition: "EXCELLENT" as const,
    categorySlug: "sofas",
    description: "Sofá de três lugares em linho lavado, assento profundo e estrutura em madeira de eucalipto.",
    image:
      "https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Sofá claro de linho em sala iluminada.",
    widthCm: 220,
    heightCm: 85,
    depthCm: 95,
  },
  {
    slug: "mesa-jantar-carvalho",
    name: "Mesa Jantar Carvalho",
    meta: "Mesa · Jantar · Carvalho",
    category: "Mesas",
    style: "Escandinavo",
    priceCents: 329000,
    brand: "Carvalho Norte",
    size: "Grande",
    color: "Natural",
    condition: "NEW_WITH_TAG" as const,
    categorySlug: "mesas",
    description: "Mesa retangular em carvalho maciço, tampo com veio aparente e base em treliça.",
    image:
      "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Mesa de jantar em madeira com seis cadeiras.",
    widthCm: 180,
    heightCm: 76,
    depthCm: 90,
  },
  {
    slug: "poltrona-ninho",
    name: "Poltrona Ninho",
    meta: "Poltrona · Leitura · Bouclé",
    category: "Cadeiras e poltronas",
    style: "Orgânico",
    priceCents: 189000,
    brand: "Ninho Studio",
    size: "Médio",
    color: "Musgo",
    condition: "EXCELLENT" as const,
    categorySlug: "cadeiras-e-poltronas",
    description: "Poltrona envelopante em bouclé, base giratória discreta e apoio cervical generoso.",
    image:
      "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Poltrona verde em canto de leitura com luminária.",
    widthCm: 78,
    heightCm: 92,
    depthCm: 82,
  },
  {
    slug: "estante-vertical-alto",
    name: "Estante Vertical Alto",
    meta: "Estante · Biblioteca · Freijó",
    category: "Estantes e racks",
    style: "Industrial suave",
    priceCents: 245000,
    brand: "Alto Linha",
    size: "Grande",
    color: "Freijó",
    condition: "VERY_GOOD" as const,
    categorySlug: "estantes-e-racks",
    description: "Estante alta com cinco prateleiras, estrutura metálica preta e nichos assimétricos.",
    image:
      "https://images.unsplash.com/photo-1594620302200-9a762244a156?auto=format&fit=crop&w=1200&q=80",
    alt: "Estante de madeira com livros e objetos decorativos.",
    widthCm: 120,
    heightCm: 210,
    depthCm: 35,
  },
  {
    slug: "cama-casal-nord",
    name: "Cama Casal Nord",
    meta: "Cama · Quarto · Madeira",
    category: "Camas",
    style: "Nórdico",
    priceCents: 279000,
    brand: "Nord Sleep",
    size: "Grande",
    color: "Branco gelo",
    condition: "EXCELLENT" as const,
    categorySlug: "camas",
    description: "Cama casal com cabeceira baixa estofada, estrutura em madeira e sommier incluso.",
    image:
      "https://images.pexels.com/photos/813691/pexels-photo-813691.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Cama casal branca em quarto minimalista.",
    widthCm: 158,
    heightCm: 105,
    depthCm: 208,
  },
  {
    slug: "rack-tv-baixo",
    name: "Rack TV Baixo",
    meta: "Rack · Sala · Nogueira",
    category: "Estantes e racks",
    style: "Mid-century",
    priceCents: 159000,
    brand: "Mareli Arte",
    size: "Médio",
    color: "Nogueira",
    condition: "GOOD" as const,
    categorySlug: "estantes-e-racks",
    description: "Rack baixo com duas gavetas e passagem para cabos, ideal para salas compactas.",
    image:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80",
    alt: "Rack de TV em madeira escura em sala moderna.",
    widthCm: 160,
    heightCm: 45,
    depthCm: 42,
  },
] as const;
